# Generated by Django 2.2.3 on 2019-07-17 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('submission_date', models.DateField()),
                ('peer_review_end_date', models.DateField()),
                ('submission_open', models.BooleanField()),
                ('peer_review_open', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Peer_review_rubrik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Assessment')),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Patch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Peer_review_submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Student')),
                ('peer_review_rubrik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Peer_review_rubrik')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Submission')),
            ],
        ),
    ]
