# Generated by Django 2.2.3 on 2019-09-09 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_original',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patch',
            name='peer_review_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='patch',
            name='submission_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='peer_review_rubrik',
            name='patch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Patch'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='patch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Patch'),
        ),
        migrations.CreateModel(
            name='Submission_edits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.TextField(null=True)),
                ('added', models.TextField(null=True)),
                ('date_time', models.DateTimeField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default='0')),
                ('value', models.DecimalField(decimal_places=5, default='1.0', max_digits=100)),
                ('script', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_round', models.IntegerField(null=True)),
                ('reliability', models.IntegerField(null=True)),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Patch')),
            ],
        ),
        migrations.CreateModel(
            name='Judgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Patch')),
                ('script_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_a', to='project.Script')),
                ('script_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='script_b', to='project.Script')),
                ('what_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Round')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Script')),
            ],
        ),
    ]
