# Generated by Django 2.2.3 on 2019-07-21 12:15

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='patch',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='text',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='title',
        ),
        migrations.AddField(
            model_name='submission',
            name='content',
            field=tinymce.models.HTMLField(default='', verbose_name='content'),
        ),
        migrations.AddField(
            model_name='submission',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
