# Generated by Django 2.2.3 on 2019-07-28 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('assignment_description', models.TextField()),
                ('submission_date', models.DateTimeField()),
                ('peer_review_date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='peer_rubrik',
            name='patch',
        ),
        migrations.AlterField(
            model_name='submission',
            name='patch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Assignment'),
        ),
        migrations.DeleteModel(
            name='Patch',
        ),
        migrations.AddField(
            model_name='peer_rubrik',
            name='assignment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.Assignment'),
            preserve_default=False,
        ),
    ]
