# Generated by Django 2.2.3 on 2019-07-28 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190728_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='patch',
            new_name='assignment',
        ),
    ]
