# Generated by Django 2.2.3 on 2019-08-20 16:15

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190819_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement',
            name='patch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Patch'),
        ),
        migrations.AlterField(
            model_name='peer_review_rubrik',
            name='patch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Patch'),
        ),
        migrations.AlterField(
            model_name='round',
            name='patch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Patch'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='patch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Patch'),
        ),
    ]
