# Generated by Django 2.2.3 on 2019-08-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_submission_edits'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_original',
            field=models.BooleanField(default=False),
        ),
    ]
