# Generated by Django 2.2.3 on 2019-08-01 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190731_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peer_review_rubrik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Peer_review_submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('peer_review_rubrik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Peer_review_rubrik')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Submission')),
            ],
        ),
        migrations.DeleteModel(
            name='Peer_rubrik',
        ),
    ]
