# Generated by Django 2.2.3 on 2019-07-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20190722_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_student',
            field=models.BooleanField(default=True, verbose_name='student'),
        ),
    ]
