# Generated by Django 2.2.3 on 2019-08-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190805_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
