# Generated by Django 2.2.3 on 2019-07-23 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190722_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patch',
            old_name='peer_review_end_date',
            new_name='peer_review_date',
        ),
        migrations.RemoveField(
            model_name='patch',
            name='peer_review_open',
        ),
        migrations.RemoveField(
            model_name='patch',
            name='submission_open',
        ),
    ]
