# Generated by Django 2.2.3 on 2019-08-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_assignment_is_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='peer_review_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='submission_date',
            field=models.DateTimeField(null=True),
        ),
    ]
