# Generated by Django 2.2.3 on 2019-08-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20190805_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission_edits',
            name='delta',
        ),
        migrations.AddField(
            model_name='submission_edits',
            name='added',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='submission_edits',
            name='deleted',
            field=models.TextField(null=True),
        ),
    ]
