# Generated by Django 2.2.3 on 2019-07-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20190723_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patch',
            name='id',
        ),
        migrations.AlterField(
            model_name='patch',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
