# Generated by Django 2.2.3 on 2019-08-11 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20190806_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_round', models.IntegerField()),
                ('reliability', models.IntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('value', models.IntegerField()),
                ('script', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='Script_judgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('script_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_a', to='project.Script')),
                ('script_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_b', to='project.Script')),
                ('what_round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.Round')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Script')),
            ],
        ),
    ]
