# Generated by Django 2.2.3 on 2019-07-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20190723_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='description',
            new_name='assessment',
        ),
        migrations.AddField(
            model_name='assessment',
            name='peer_rubrik',
            field=models.TextField(blank=True),
        ),
    ]
