# Generated by Django 2.2.3 on 2019-07-24 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20190724_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='peer_rubrik',
        ),
        migrations.CreateModel(
            name='Peer_rubrik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_rubrik_text', models.TextField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Assessment')),
            ],
        ),
    ]
