# Generated by Django 2.2.3 on 2019-08-12 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_round_script_script_judgement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='round',
            name='reliability',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='what_round',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='value',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Script_judgement',
        ),
        migrations.AddField(
            model_name='judgement',
            name='script_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_a', to='project.Script'),
        ),
        migrations.AddField(
            model_name='judgement',
            name='script_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_b', to='project.Script'),
        ),
        migrations.AddField(
            model_name='judgement',
            name='what_round',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.Round'),
        ),
        migrations.AddField(
            model_name='judgement',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Script'),
        ),
    ]
