# Generated by Django 2.2.3 on 2019-07-24 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20190724_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patch',
            name='end_date',
        ),
    ]
