# Generated by Django 2.2.3 on 2019-08-12 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20190812_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement',
            name='script_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='script_b', to='project.Script'),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='what_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Round'),
        ),
    ]
