# Generated by Django 2.2.3 on 2019-07-24 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_remove_patch_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peer_review_rubrik',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='peer_review_submission',
            name='author',
        ),
        migrations.RemoveField(
            model_name='peer_review_submission',
            name='peer_review_rubrik',
        ),
        migrations.RemoveField(
            model_name='peer_review_submission',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='peer_rubrik',
            name='assessment',
        ),
        migrations.AddField(
            model_name='patch',
            name='assignment_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patch',
            name='assignment_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peer_rubrik',
            name='patch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.Patch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='patch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.Patch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.Student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peer_rubrik',
            name='peer_rubrik_text',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='Peer_review_rubrik',
        ),
        migrations.DeleteModel(
            name='Peer_review_submission',
        ),
    ]
