# Generated by Django 2.2.3 on 2019-08-13 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20190813_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgement',
            name='assignment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.Assignment'),
            preserve_default=False,
        ),
    ]
