# Generated by Django 2.2.3 on 2019-07-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20190725_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patch',
            name='peer_review_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='patch',
            name='submission_date',
            field=models.DateTimeField(),
        ),
    ]
