# Generated by Django 2.2.3 on 2019-08-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_judgement_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='value',
            field=models.IntegerField(default='1'),
        ),
    ]
