# Generated by Django 2.2.3 on 2019-08-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20190814_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='value',
            field=models.DecimalField(decimal_places=5, default='1.0', max_digits=100),
        ),
    ]
